### ISSUE TITLE
Publish releases on GitHub

### ISSUE THREAD

**Issue by baptiste0928** [ENQT-GmbH/remoc#10]
I noticed that release changelog is only available in the [ `CHANGELOG.md` ](https://github.com/ENQT-GmbH/remoc/blob/master/CHANGELOG.md) file. I think it would be nice to [publish them as GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) too, as this allows you to quickly see when the last version was made and therefore if the project is active. It also allows people interested in `remoc` to watch releases and get notified when a new version is available.

**Comment by surban** [comment]
Ok, done.

Too bad GitHub cannot generate a release from CHANGELOG.md.
