### ISSUE TITLE
Using remoc on wasm fails due to unsupported tokio::time::Instant

### ISSUE THREAD

**Issue by giacomocariello** [ENQT-GmbH/remoc#12]
When trying to use remoc on browser, it panics because it calls tokio::time::timeout, which is based on tokio::time::Instant::now, which in turns calls std::time::Instant, which is not supported on browser. Could you consider replacing it with an implementation that supports both tokio::time (on supported platforms) and wasm time (on browsers)?
For instance, please take a look at https://crates.io/crates/instant implementation.

**Comment by surban** [comment]
Hi,

thanks for trying to get Remoc to work with WASM. I have not tried myself yet but would be willing to accept pull requests that make it work with WASM.

Are you sure that `Instant` is the only thing blocking Remoc on WASM? I suspect that `tokio::spawn` is also not working, which would be a much bigger issue.

**Comment by surban** [comment]
I am closing this for now, because currently the prerequirements for supporting WASM are not present. Once Tokio supports spawning tasks on WASM we will implement WASM support in Remoc.

**Comment by surban** [comment]
Remoc now supports WebAssembly targets (`wasm32-unknown-unknown` and also `wasm32-wasip1-threads`) since version 0.15. You must enable the `js` crate feature if you are targeting a JavaScript runtime environment, i.e. a web browser.
