### ISSUE TITLE
Macro error with Rust 1.70.0

### ISSUE THREAD

**Issue by giacomocariello** [ENQT-GmbH/remoc#17]
I've recently rebuilt some code with latest stable rust and encountered this error:

```
error: impl method assumes more implied bounds than the corresponding trait method
 --> src/library/rpc.rs:8:1
  |
8 | #[rtc::remote]
  | ^^^^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #105572 <https://github.com/rust-lang/rust/issues/105572>
  = note: `#[deny(implied_bounds_entailment)]` on by default
  = note: this error originates in the attribute macro `rtc::remote` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0412, E0432.
For more information about an error, try `rustc --explain E0412`.
```

**Comment by giacomocariello** [comment]
The problem was actually in my code, but the error was quite cryptic/unexpected.

**Comment by surban** [comment]
It's quite difficult to provide good error messages in proc macros.

The best advise is actually  what the compiler is giving you:
`  = note: this error originates in the attribute macro rtc::remote (in Nightly builds, run with -Z macro-backtrace for more info)`

**Comment by giacomocariello** [comment]
Yup. Unluckily the nightly build wasn't really more explicit about the cause. In this case, IMHO, the problem is not the macro or remoc at all, but rustc compiler, because this linter-turned-error misrepresents the real error in the specific case I encountered, even on non-macro situations. I'll comment on appropriate issue on rust-lang asap.

**Comment by surban** [comment]
BTW if you're having trouble with Send + Sync bounds on the RTC server, you could try [version 0.11](https://github.com/ENQT-GmbH/remoc/blob/master/CHANGELOG.md).
