### ISSUE TITLE
Support for Postcard as an encoding format

### ISSUE THREAD

**Issue by Firaenix** [ENQT-GmbH/remoc#19]
Hi,

I love your library! I've used it myself to build a distributed database and its worked so well for me in the past. 
However, I've been playing around a lot with https://github.com/jamesmunns/postcard and have had a lot of success with it in regards to size & performance and was wondering what the best way would be to use this with Remoc?

**Comment by surban** [comment]
Great, that remoc is useful to you!

Since Postcard is a serde codec, it should be straightforward to add it to the [supported codecs](https://github.com/ENQT-GmbH/remoc/tree/master/remoc/src/codec) and add the necessary features to `Cargo.toml`.

Could you send a PR, if possible?

**Comment by Firaenix** [comment]
Yep that should be possible, I'll put aside some time tomorrow to create the PR

**Comment by Firaenix** [comment]
Hi,

I've completed the PR here: https://github.com/ENQT-GmbH/remoc/pull/20

**Comment by surban** [comment]
Fixed in #20
