### ISSUE TITLE
Compile error with lifetimes on remote traits

### ISSUE THREAD

**Issue by baptiste0928** [ENQT-GmbH/remoc#4]
The `rtc::remote` attribute make a compilation error when used on a trait with lifetimes. This happen for example when using a `Cow` as return type to avoid unnecessary allocations.

## Example

```rust
#[rtc::remote]
pub trait ExampleBorrowed {
    async fn hello(&self) -> Result<Cow<'_, String>, CallError>;
}
```
<details>
  <summary><strong>Compiler error</strong></summary>
  
  ```
  error[E0106]: missing lifetime specifier
    --> transport/src/cache.rs:45:41
     |
  45 |     async fn hello(&self) -> Result<Cow<'_, String>, CallError>;
     |                                         ^^ expected named lifetime parameter
     |
  help: consider introducing a named lifetime parameter
     |
  43 ~ 'a, #[rtc::remote]
  44 | pub trait ExampleBorrowed {
  45 ~     async fn hello(&self) -> Result<Cow<'a, String>, CallError>;
     |
  ```
</details>

The compiler expect a named lifetime, while it can be elided in this case. When a named lifetime is provided, another compile errors occurs.

<details>
  <summary><strong>Compiler error with named lifetime</strong></summary>
  
  With function lifetime:
  ```rust
  #[rtc::remote]
  pub trait ExampleBorrowed {
      async fn hello<'a>(&self) -> Result<Cow<'a, String>, CallError>;
  }
  ```

  ```
  error: expected parentheses
    --> transport/src/cache.rs:44:19
     |
  44 |     async fn hello<'a>(&self) -> Result<Cow<'a, String>, CallError>;
     |    
  ```

  With trait lifetime:

  ```rust
  #[rtc::remote]
  pub trait ExampleBorrowed<'a> {
      async fn hello(&self) -> Result<Cow<'a, String>, CallError>;
  }
  ```

  ```
  error: lifetime in trait object type must be followed by `+`
    --> transport/src/cache.rs:43:27
     |
  43 | pub trait ExampleBorrowed<'a> {
     |                           ^^
  
  error: expected at least one type
    --> transport/src/cache.rs:42:1
     |
  42 | #[rtc::remote]
     | ^^^^^^^^^^^^^^
     |
     = note: this error originates in the attribute macro `rtc::remote` (in Nightly builds, run with -Z macro-backtrace for more info)
  
  error[E0782]: trait objects must include the `dyn` keyword
    --> transport/src/cache.rs:43:27
     |
  43 | pub trait ExampleBorrowed<'a> {
     |                           ^^
     |
  help: add `dyn` keyword before this trait
     |
  43 | pub trait ExampleBorrowed<dyn 'a> {
     |                           +++
  
  error[E0224]: at least one trait is required for an object type
    --> transport/src/cache.rs:43:27
     |
  43 | pub trait ExampleBorrowed<'a> {
     |   
  ```
</details>

**Comment by surban** [comment]
Hi!

I am not sure how we could make this work. In my understanding a lifetime implies a reference which would in that case cross the boundary between two processes, possibly running on different machines. 

Could you elaborate what you are trying to achieve? In any case the client will need to somehow put a copy of the result in its memory, thus allocating.

**Comment by baptiste0928** [comment]
I'm using remote traits to expose a cache to multiple services. I wanted to avoid cloning data in the server side by using a `Cow` as return type (as `Cow` implement `DeserializeOwned` and `Serialize` doesn't need an owned value). In this case, the client would receive an owned value with `Cow::Owned`, so the reference will not be shared between two processes.

Anyway I reported this issue in case it can easily be solved, allocating is not a problem for my use case, it's more micro-optimization.

**Comment by surban** [comment]
Remote trait calling is implemented by sending and receiving messages over remote channels, which require that all transmitted data is `RemoteSend` which itself requires `'static` lifetime. So even if we start allowing lifetimes in remote traits, this would constrain them to be `'static` and thus does not be very useful.

At the moment I don't think there is an easy fix, but you should be able to send and receive `Arc` pointers once you enable the corresponding `serde` feature.

**Comment by baptiste0928** [comment]
That's right, I forgot about the `'static` lifetime requirement. I'm going to try it with `Arc`, it's a great idea. Thanks for your answers!

**Comment by surban** [comment]
Once you get your project working, would you be willing to blog about it and release some code as an example? Remoc has doc-examples but is missing a fully worked example project that shows how all fits together.

**Comment by baptiste0928** [comment]
Yes, I will do it when my project is released :+1:
